name: traqer
description: Eng thesis proj

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '3.2.6'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.0.0
  geolocator_android: ^4.5.4
  gpx: ^2.2.1
  path_provider: ^2.1.1
  open_settings: ^2.0.2
  permission_handler: ^11.1.0
  flutter_speed_dial: ^7.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  location: ^5.0.0
  cupertino_icons: ^1.0.2
  flutter_map_location_marker: ^8.0.4
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true
